// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Kernel.Stubs1;

namespace Kernel.Stubs1
{

    public class Body
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("devices")]
        public Device[] Devices { get; set; }

        [JsonProperty("rooms")]
        public Room[] Rooms { get; set; }

        [JsonProperty("doors")]
        public Door[] Doors { get; set; }

        [JsonProperty("metavalues")]
        public Metavalues3 Metavalues { get; set; }
    }

}
