// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Kernel.Stubs1;

namespace Kernel.Stubs1
{

    public class EventbusMessage
    {

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("mode")]
        public string Mode { get; set; }

        [JsonProperty("bodyType")]
        public string BodyType { get; set; }

        [JsonProperty("senderId")]
        public string SenderId { get; set; }

        [JsonProperty("body")]
        public Body Body { get; set; }
    }

}
