// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Kernel.Stubs1;

namespace Kernel.Stubs1
{

    public class Metavalues3
    {

        [JsonProperty("DESCRIPTION")]
        public DESCRIPTION2 DESCRIPTION { get; set; }

        [JsonProperty("ADDRESS")]
        public ADDRESS ADDRESS { get; set; }

        [JsonProperty("GATEWAYS")]
        public GATEWAYS GATEWAYS { get; set; }
    }

}
