// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Kernel.Stubs;

namespace Kernel.Stubs
{

    public class Device
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("type")]
        public int Type { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("roomId")]
        public int RoomId { get; set; }

        [JsonProperty("coordinate")]
        public Coordinate Coordinate { get; set; }

        [JsonProperty("areaCoordinates")]
        public object[] AreaCoordinates { get; set; }

        [JsonProperty("metavalues")]
        public Metavalues Metavalues { get; set; }
    }

}
