// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Kernel.Stubs;

namespace Kernel.Stubs
{

    public class Door
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("coordinates")]
        public Coordinate[] Coordinates { get; set; }

        [JsonProperty("rooms")]
        public Room[] Rooms { get; set; }
    }

}
