// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Kernel.Stubs;

namespace Kernel.Stubs
{

    public class Metavalues
    {

        [JsonProperty("HARDWARE_ID")]
        public HARDWAREID HARDWAREID { get; set; }

        [JsonProperty("CONFIGURATION")]
        public CONFIGURATION CONFIGURATION { get; set; }

        [JsonProperty("MANUFACTURER")]
        public MANUFACTURER MANUFACTURER { get; set; }

        [JsonProperty("GATEWAY")]
        public GATEWAY GATEWAY { get; set; }
    }

}
